### ISSUE TITLE
Node.js 15 compatibility

### ISSUE THREAD

**Issue by piranna** [RichardLitt/standard-readme-preset#38]
https://github.com/RichardLitt/standard-readme-preset/blob/9a525557875c0f47fbacfbe54917adabde02cf11/package.json#L31

Change engines field to add support for Node.js 15.

**Comment by RichardLitt** [comment]
PRs accepted. Thanks for pointing this out.

**Comment by piranna** [comment]
At https://github.com/RichardLitt/standard-readme-preset/blob/eb594da2645d21482b173bd4119519287d7a3e53/package.json#L31 it shows already support Node.js 15, so this could be closed, but maybe it's not the best solution and we would need to use ranges instead... what do you think?

**Comment by RichardLitt** [comment]
Ranges should work. Not sure why we're skipping 11. I'm also unsure of how useful this field is, anyway; I know I haven't used it, personally.

**Comment by wooorm** [comment]
I'd strongly suggest something like '>=10' or so. It makes sure that every future release is allowed. If something doesn't work, folks will raise issues anyway 🤷‍♂️

**Comment by RichardLitt** [comment]
Sounds good to me! @piranna want to PR?

**Comment by piranna** [comment]
> Sounds good to me! @piranna want to PR?

https://github.com/RichardLitt/standard-readme-preset/pull/42

Here you have it :-)
